#
#		DO NOT EDIT THIS FILE 
#
#

ifdef .MAKE_VERSION
.error "BSD make detected. This project requires GNU make (gmake). Please install gmake and run 'gmake' instead of 'make'."
endif

SHELL = /bin/sh
top_srcdir = .
srcdir = .



CCDEPMODE = gcc3
BINEXEC = wraith

STATICMAKEFILES = lib/Makefile src/Makefile Makefile
CONFIGFILES = build/config.cache build/config.log build/config.status src/config.h src/buildinfo.h

DISTROFILES = README.md LICENSE build doc scripts lib Makefile.in build.sh configure src BSDmakefile
EXCLUDES = $(CONFIGFILES) $(STATICMAKEFILES)

COMMIT_FULL 	:= $(shell git log -1 --pretty=format:%H HEAD)
COMMIT_SHORT 	:= $(shell git log -1 --pretty=format:%h HEAD)
BRANCH 		:= $(shell git branch --no-color | grep "^*" | sed -e 's/^\* //')
BUILDTS 	:= $(shell git log -1 --pretty=format:%ct HEAD)
VERSION 	:= $(shell git describe --candidates=2)
DISTRIB = wraith-$(VERSION)

HELPFILE = doc/help.txt

# defaults
CXX = clang++ -std=c++11 -std=c++14 -pipe
CC = clang++ -x c
LD_DYNAMIC = clang++ -std=c++11 -std=c++14 -pipe
LD_DEBUG = clang++ -std=c++11 -std=c++14 -pipe
STRIP = strip
DIFF = diff

#LIBS = -ldl 
LIBS = -ldl 
INCLUDES = -I/usr/include -DOPENSSL_API_COMPAT=0x10000000L

DEBCXXFLAGS = -DDEBUG -fno-inline -g3 -ggdb3 -fno-omit-frame-pointer -fno-optimize-sibling-calls -Wshadow -Wpointer-arith -Wno-disabled-optimization -Wmissing-format-attribute -Wwrite-strings -Wformat -Wformat-security   -Og -fstack-protector-all -Wconditional-uninitialized
DEBLDFLAGS= 
CFLGS = -W -Wno-unused-parameter -Wdisabled-optimization -Wno-write-strings -Wno-format-security -Wno-format-y2k
CXXFLAGS = $(CFLGS) -g -O2 -Wall -fcolor-diagnostics -Wno-invalid-source-encoding -Wno-narrowing -Wno-cast-function-type -Wno-cast-function-type-mismatch -Wno-cast-function-type-strict -fstack-protector -fstack-protector-strong -Woverloaded-virtual -fno-rtti

MAKEFLAGS = -s

MAKE_DYNAMIC = $(MAKE) 'MAKE=$(MAKE)' 'CXX=$(CXX)' 'CC=$(CC)' 'LD=$(LD_DYNAMIC)' 'INCLUDES=$(INCLUDES)' \
'CCDEPMODE=$(CCDEPMODE)' 'BRANCH=$(BRANCH)' 'COMMIT=$(COMMIT_SHORT)' 'BUILDTS=$(BUILDTS)' 'VERSION=$(VERSION)' \
'STRIP=$(STRIP)' 'CXXFLAGS=$(CXXFLAGS)' 'CFLGS=$(CFLGS) -DBIN_TYPE_DYNAMIC' \
'LIBS=$(LIBS)' 'EGGEXEC=$(BINEXEC)' 'EGGBUILD=(wraith)'

MAKE_DEBUG = $(MAKE) 'MAKE=$(MAKE)' 'CXX=$(CXX)' 'CC=$(CC)' 'LD=$(LD_DEBUG) -g' 'INCLUDES=$(INCLUDES)' \
'CCDEPMODE=$(CCDEPMODE)' 'BRANCH=$(BRANCH)' 'COMMIT=$(COMMIT_SHORT)' 'BUILDTS=$(BUILDTS)' 'VERSION=$(VERSION)' \
'STRIP=touch' 'CXXFLAGS=$(CXXFLAGS) $(DEBCXXFLAGS)' 'CFLGS=$(CFLGS) $(DEBCXXFLAGS) -DBIN_TYPE_DYNAMIC' \
'DEBLDFLAGS=$(DEBLDFLAGS)' 'LIBS=$(LIBS)' 'EGGEXEC=$(BINEXEC)' 'EGGBUILD=(debug)'

MAKE_UTILS = $(MAKE) 'MAKE=$(MAKE)' 'CXX=$(CXX)' 'CC=$(CC)' 'STRIP=touch' 'INCLUDES=$(INCLUDES)' \
'CCDEPMODE=$(CCDEPMODE)' 'DEBLDFLAGS=$(DEBLDFLAGS)' \
'CXXFLAGS=$(CXXFLAGS) $(DEBCXXFLAGS)' 'CFLGS=$(CFLGS) $(DEBCXXFLAGS)' 'LIBS=$(LIBS)' 'LD=$(LD_DEBUG) -g'

.PHONY: checkclean.dynamic checkclean.debug lib wraith lib.debug debug test general sorthelp sort indent tar distrib distclean clean cleanutils test all dynamic tags libdefs

all: dynamic

test:
	+@cd lib && $(MAKE) test

cleanutils:
	@rm -f src/sorthelp

clean:  cleanutils
	+@cd src && $(MAKE) clean
	-+@cd lib && $(MAKE) clean
	@rm -f src/.defs/*.stamp
	@rm -f $(BINEXEC) build/stamp.* *~ src/*~ configure.temp .mangled stamp.*
	@rm -f ts

distclean: clean
	@rm -rf *-$(VERSION)/ autom4te.cache/ autoscan.log configure.scan
	@rm -rf src/.deps/ src/compat/.deps/ src/strucutres/.deps/ src/mod/*.mod/.deps/ src/crypto/.deps src/.defs/
	-+@cd lib && $(MAKE) distclean
	@rm -f $(STATICMAKEFILES) $(CONFIGFILES) config.h config.log config.status


distrib: clean
	@rm -rf $(DISTRIB)/
	-+@cd lib && $(MAKE) distclean
	@mkdir $(DISTRIB) && cp -R $(DISTROFILES) $(DISTRIB)
	@rm -rf `find $(DISTRIB)/ \( -name '*~' -o -name '*#' -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' -o -name '.gitignore' -o -name '.*.swp' \) -type f -print`
	@rm -rf `find $(DISTRIB)/ \( -name '.git' -o -name '.deps' \) -type d -print`
	@for s in $(EXCLUDES); do \
	 rm -rf $(DISTRIB)/$$s; \
	done;
	@sed \
	  -e 's/^COMMIT_FULL .*/COMMIT_FULL = $(COMMIT_FULL)/' \
	  -e 's/^COMMIT_SHORT .*/COMMIT_SHORT = $(COMMIT_SHORT)/' \
	  -e 's/^BRANCH .*/BRANCH = $(BRANCH)/' \
	  -e 's/^BUILDTS .*/BUILDTS = $(BUILDTS)/' \
	  -e 's/^VERSION .*/VERSION = $(VERSION)/' \
	  $(DISTRIB)/Makefile.in > Makefile.in.tmp && mv Makefile.in.tmp $(DISTRIB)/Makefile.in
	@sed -e 's/GIT_REQUIRED=1/GIT_REQUIRED=0/' configure > $(DISTRIB)/configure
#	@for s in `find $(DISTRIB)/src/ -name '*.h' -or -name '*.c'`; do mangle -rnw $$s > /dev/null 2>&1; done

tags:
	@which cscope >/dev/null 2>&1 && cscope -Rbq || :
	@which ctags >/dev/null 2>&1 && ctags -R || :

tar: distrib
	tar -czvf $(DISTRIB).tar.gz $(DISTRIB)/
	ls -al $(DISTRIB).tar.gz
#	rm -rf $(DISTRIB)/
#	cd ../ && rm -rf distrib/

indent:
	@ifiles="`find src -name '*.h' -or -name '*.c'`"; \
	for s in $$ifiles; \
	do \
	 INDENT_PROFILE=private/indent.pro indent $$s; \
	done

sort: sorthelp
	@(if test "x`tail -n 1 $(HELPFILE)`" != "x::end"; then \
	echo "::end" >> $(HELPFILE); \
	fi)
#	@(sed $(HELPFILE) -e "s/^$$/ /" > help~ && mv -f help~ $(HELPFILE)) || rm -f help~
	@(sed -r -e :a -e 's/^$$/ /' -e '$$!N;s/^ \n:/:/;ta' -e 'P;D' $(HELPFILE) > help~ && mv -f help~ $(HELPFILE)) || rm -f help~
	@cp -f $(HELPFILE) help.txt~
	@(src/sorthelp $(HELPFILE) $(HELPFILE) || (cp -f help.txt~ $(HELPFILE); echo "Sort failed, restoring backup."))
	@rm -f help.txt~

sorthelp: src/sorthelp.cc
	+@cd src && ${MAKE_UTILS} sorthelp

libdefs: src/.defs/libcrypto_post.h src/.defs/libssl_post.h \
	 src/.defs/libcrypto_pre.h src/.defs/libssl_pre.h \
	 src/.defs/libcrypto_exports src/.defs/libssl_exports
src/.defs/libcrypto_post.h src/.defs/libcrypto_pre.h src/.defs/libcrypto_exports: src/.defs/libcrypto_gen.stamp
src/.defs/libcrypto_gen.stamp: src/libcrypto.cc \
	src/generate_defs.sh src/generate_symbol.sh src/dl.h
	@CXX="$(CXX)" CXXFLAGS="$(CXXFLAGS)" INCLUDES="$(INCLUDES)" \
           SED="sed" src/generate_defs.sh src/libcrypto.cc || exit 1
	@touch $@
src/.defs/libssl_post.h src/.defs/libssl_pre.h src/.defs/libssl_exports: src/.defs/libssl_gen.stamp
src/.defs/libssl_gen.stamp: src/libssl.cc \
	src/generate_defs.sh src/generate_symbol.sh src/dl.h
	@CXX="$(CXX)" CXXFLAGS="$(CXXFLAGS)" INCLUDES="$(INCLUDES)" \
           SED="sed" src/generate_defs.sh src/libssl.cc || exit 1
	@touch $@
src/.defs/exports: Makefile \
	src/.defs/libcrypto_gen.stamp src/.defs/libssl_gen.stamp
	@echo "Generating $@"
	@{ \
		echo "{"; \
		echo "bfd_exports_stub;"; \
		cat src/.defs/*_exports; \
		echo "};"; \
	} > $@.tmp
	@if ! cmp -s $@.tmp $@; then \
		mv -f $@.tmp $@; \
	else \
		rm -f $@.tmp; \
		touch $@; \
	fi

general: libdefs src/.defs/exports

.NOTPARALLEL: checkclean.dynamic checkclean.debug

checkclean.dynamic:
	@(if test -f build/stamp.debug; then \
	echo "[*] Cleaning up alternate build"; \
	$(MAKE) MAKEFLAGS=-s clean; \
	fi)
	@touch build/stamp.dynamic

checkclean.debug:
	@(if test -f build/stamp.dynamic; then \
	echo "[*] Cleaning up alternate build"; \
	$(MAKE) MAKEFLAGS=-s clean; \
	fi)
	@touch build/stamp.debug

lib:
	+@cd lib && $(MAKE)

dynamic: checkclean.dynamic lib general
	@echo ""
	@echo "Making dynamic binary"
	@echo ""
	+@cd src && $(MAKE_DYNAMIC) ../$(BINEXEC)


lib.debug:
	+@cd lib && $(MAKE) debug

debug: checkclean.debug lib.debug general
	@echo ""
	@echo "Making debug binary"
	@echo ""
	+@cd src && $(MAKE_DEBUG) ../$(BINEXEC)

#safety hash

